# Generated by Django 5.0 on 2023-12-24 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_key",
            field=models.CharField(
                default="TDqYWyRkc4qXLjssEv81kOFunpD178EU",
                editable=False,
                max_length=24,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=45, null=True)),
                (
                    "series_movie",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
                ("part", models.IntegerField(blank=True, null=True)),
                ("season", models.IntegerField(blank=True, null=True)),
                ("episode", models.IntegerField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=45, null=True)),
                ("quality", models.CharField(blank=True, max_length=45, null=True)),
                ("file_id", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
