# Generated by Django 5.0 on 2023-12-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0002_alter_client_client_key_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="file_size",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_key",
            field=models.CharField(
                default="G1zTyM0cX8UreNLMxGG5oEk8DoL5TeV-",
                editable=False,
                max_length=24,
                unique=True,
            ),
        ),
    ]
