# Generated by Django 5.0 on 2023-12-27 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0003_file_file_size_file_year_alter_client_client_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="Forwarded_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="client_key",
            field=models.CharField(
                default="rusHQeAhfRzF10www78C450HaxPEVxnT",
                editable=False,
                max_length=24,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="verified_groups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_id", models.CharField(blank=True, max_length=45)),
                (
                    "forwardedcount_for_group",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
