# Generated by Django 5.0 on 2023-12-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0004_file_forwarded_count_alter_client_client_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_key",
            field=models.CharField(
                default="hOw7iLfG-hPly1kNRfkYyYp5FNdqTMWu",
                editable=False,
                max_length=24,
                unique=True,
            ),
        ),
    ]
