# Generated by Django 5.0 on 2023-12-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0006_alter_client_client_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_key",
            field=models.CharField(
                default="9NphZXpqSoN14R_FTaCCciEEiy-9UFUL",
                editable=False,
                max_length=24,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="Forwarded_count",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
