# Generated by Django 5.0 on 2023-12-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link_to_file",
            name="param",
            field=models.CharField(
                default="R_WSmZux9KNQv_gb", editable=False, max_length=24, unique=True
            ),
        ),
    ]
