# Generated by Django 5.0 on 2023-12-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_alter_link_to_file_param"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link_to_file",
            name="param",
            field=models.CharField(
                default="R3r_yiN0qsZhbALg", editable=False, max_length=12, unique=True
            ),
        ),
    ]
