# Generated by Django 5.0 on 2023-12-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_alter_link_to_file_param"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link_to_file",
            name="param",
            field=models.CharField(
                default="eTdK_6g9q3T-fGLs", editable=False, max_length=12, unique=True
            ),
        ),
    ]
